#  * 1.0.0 for a first major release.
#  * 0.1.0 for a breaking release.
#  * 0.0.4 for a minor release.
name: approval_tests
description: Approval Tests implementation in Dart. Inspired by ApprovalTests.
version: 1.4.3
repository: https://github.com/approvals/ApprovalTests.Dart
homepage: https://github.com/approvals/ApprovalTests.Dart.git
issue_tracker: https://github.com/approvals/ApprovalTests.Dart/issues

topics:
  - test
  - approval
  - approvals
  - tests
  - approval-tests

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.16.0
  test: ^1.25.0
  talker: ^5.0.2
  diff_match_patch2: ^0.5.0
  test_api: ^0.7.4

dev_dependencies:
  sizzle_lints: ^2.1.7
